Module3 task2
htmlacademy-nodejs/423185-keksobooking pull request #7
Opened 2018-10-06 16:39 UTC by AntonLantukh

2018-10-06 17:33 UTC, zkbpkp requested changes

2018-10-06 17:33 UTC, KolesnichenkoDS commented on test/generate.test.js
> +    assert.ok(file.offer.rooms > 1 && file.offer.rooms < 5);
Тут ты выкидываешь 1 и 5, надо `file.offer.rooms >= 1 && file.offer.rooms <= 5`

2018-10-06 17:33 UTC, KolesnichenkoDS commented on test/generate.test.js
> +    assert.ok(file.offer.guests > 1 && file.offer.guests < 5);
То же что и выше

2018-10-06 17:33 UTC, KolesnichenkoDS commented on test/generate.test.js
> +  generateFile();
Это же асинхронная функция, она возвращает промис — надо удостовериться в том что она отработала перед тем как делать что-то ещё

https://lostechies.com/derickbailey/2012/08/17/asynchronous-unit-tests-with-mocha-promises-and-winjs/

2018-10-06 17:36 UTC, KolesnichenkoDS commented on src/generator/generate.js
> +      fs.writeFile(`${path}/generatedData.json`, JSON.stringify(data), fileWriteOptions, (err) => {
Здесь и в других местах можно использовать `path.join` вместо ручного склеивание путей — так можно избежать некоторых проблем с кроссплатформенностью

2018-10-06 17:43 UTC, KolesnichenkoDS commented on test/generate.test.js
> +  generate.execute(TEMP_DIR);
`execute` возвращает промис — его надо дождаться

2018-10-06 17:44 UTC, KolesnichenkoDS commented on test/generate.test.js
> +  generate.execute(TEMP_DIR);
```javascript
const generateFile = async () => {
  await generate.execute(TEMP_DIR);
  return new Promise((success, fail) => { ... });
}
```

2018-10-06 17:48 UTC, KolesnichenkoDS commented on test/generate.test.js
> +  generateFile();
```javascript
beforeEach(done => {
  generateFile().then(() => done());
});
```

2018-10-08 04:59 UTC, zkbpkp requested changes

2018-10-08 04:59 UTC, zkbpkp commented on test/generate.test.js
> +      fs.readFile(path.join(TEMP_DIR, `/generatedData.json`), `utf8`, (err, fd) => {
Не нужен слеш в начале имени файла

2018-10-08 04:59 UTC, zkbpkp commented on test/generate.test.js
> +    assert.ok(file.location.x > 300 && file.location.x < 900);
Тут тоже должно быть нестрогое сравнение

2018-10-08 04:59 UTC, zkbpkp commented on test/generate.test.js
> +    assert.ok(file.location.y > 150 && file.location.y < 500);
И тут проблема со строгим/нестрогим сравнением

2018-10-08 04:59 UTC, zkbpkp commented on test/generate.test.js
> +    generate.execute(TEMP_DIR).then(() => {
Можно и так, хотя мне вариант с `async/await` кажется симпатичнее. Ты его не использовал потому что не разобрался или просто этот вариант кажется правильнее/понятнее?

2018-10-08 04:59 UTC, KolesnichenkoDS commented on test/generate.test.js
> +    assert.ok(file.offer.price > 1000 && file.offer.price < 1000000);
🙂

2018-10-08 05:01 UTC, KolesnichenkoDS commented on src/data/raw-data.js
> +const placeTitle = [
По неймингу — тут уместнее множественное число

2018-10-08 05:03 UTC, KolesnichenkoDS commented on src/data/util.js
> +'use strict';
Можно сюда добавить что-нибудь типа

```javascript
const randomChoice = (arr) => arr[generateRandomInteger(0, arr.length - 1)];
```

и использовать в `src/data/entity.js`

2018-10-08 05:09 UTC, KolesnichenkoDS commented on src/generator/generate.js
> +  execute(gotPath = CURRENT_PATH) {
Дефолтный параметр тут не нужен

2018-10-08 05:09 UTC, KolesnichenkoDS commented on src/generator/generate.js
> +      fs.writeFile(path.join(gotPath, `/generatedData.json`), JSON.stringify(data), {encoding: `utf-8`}, (err) => {
Слеш в начале имени файла лишний

2018-10-08 05:10 UTC, KolesnichenkoDS commented on src/generator/generate.js
> +const data = generateEntity();
Так данные будут генерироваться только один раз, мне кажется правильнее будет если они будут генерироваться каждый раз при вызове `execute`

2018-10-08 05:10 UTC, KolesnichenkoDS commented on src/generator/generate.js
> +  execute(gotPath = CURRENT_PATH) {
Иии нейминг неудачный на самом деле

2018-10-08 05:12 UTC, KolesnichenkoDS commented on src/data/entity.js
> +const functions = require(`./util`);
`functions` какое-то не особо удачное имя, лучше уж `util`

2018-10-08 05:14 UTC, KolesnichenkoDS commented on src/data/entity.js
> +const location = {
`location` и остальные значения генерируется один раз при импорте модуля.
Лучше сделать чтобы они генерировались каждый раз при вызове `generateEntity`

2018-10-08 05:29 UTC, KolesnichenkoDS commented on src/data/util.js
> +  const sevenDays = 604800;
Это секунды а надо миллисекунды вычитать

2018-10-08 05:31 UTC, KolesnichenkoDS commented on src/data/util.js
> +  const sevenDays = 604800;
Ну и дата должна случайно генерироваться

2018-10-09 18:56 UTC, zkbpkp requested changes

2018-10-09 18:56 UTC, KolesnichenkoDS commented on src/default.js
> +      Эта программа будет генерировать данные.
Это круто что ты нашёл применение "лишней" фиче) Но тебе потом эту штуку с генерированием данных все равно обратно выпиливать потому что использоваться она будет по-другому.
В общем инициатива это круто но лишний раз лучше не переусложнять, а то ты как-то всё дальше уходишь от ТЗ)

2018-10-09 18:56 UTC, KolesnichenkoDS commented on src/console-interface.js
> +const readline = require(`readline`);
Теперь у тебя этот ридлайн-интерфейс появляется даже когда не надо, например при отображении `--help`.

2018-10-09 18:56 UTC, KolesnichenkoDS commented on test/generate.test.js
> +      file = JSON.parse(fd);
Ну это плохая практика, лучше возвращать `file` из промиса: `success(JSON.parse(fd));`

2018-10-09 18:56 UTC, KolesnichenkoDS commented on test/generate.test.js
> +    .then(() => {
И тут соответственно чейнить `.then((file) => { ... })`

2018-10-09 18:56 UTC, KolesnichenkoDS commented
В целом — уходишь от ТЗ и это как-то не очень круто, типа ну теперь когда разобрался почему были проблемы с записью в файл я бы её убрал и в тестах оставил чистую логику типа сгенерировал объект — проверил поля, без какого-то I/O. Понятно что обидно выкидывать фичу, ноо ТЗ на то и ТЗ, что ему надо следовать)

2018-10-10 10:24 UTC, merged